<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="11" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="171" started-at="2016-11-27T12:37:57Z" finished-at="2016-11-27T12:37:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="171" started-at="2016-11-27T12:37:57Z" finished-at="2016-11-27T12:37:57Z">
      <class name="com.iiitb.MainClass">
        <test-method status="PASS" signature="checkTest()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="checkTest" duration-ms="13" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTest -->
        <test-method status="PASS" signature="testCheck1()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck1" duration-ms="3" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck1 -->
        <test-method status="FAIL" signature="testCheck10()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck10" duration-ms="2" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <exception class="org.junit.internal.ArrayComparisonFailure">
            <message>
              <![CDATA[arrays first differed at element [3]; expected:<34> but was:<344>]]>
            </message>
            <full-stacktrace>
              <![CDATA[arrays first differed at element [3]; expected:<34> but was:<344>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:416)
	at org.junit.Assert.assertArrayEquals(Assert.java:427)
	at com.iiitb.MainClass.testCheck10(MainClass.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.AssertionError: expected:<34> but was:<344>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.internal.ArrayComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck10 -->
        <test-method status="PASS" signature="testCheck2()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck2" duration-ms="2" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck2 -->
        <test-method status="PASS" signature="testCheck3()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck3" duration-ms="1" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck3 -->
        <test-method status="PASS" signature="testCheck4()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck4" duration-ms="4" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck4 -->
        <test-method status="PASS" signature="testCheck5()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck5" duration-ms="1" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck5 -->
        <test-method status="PASS" signature="testCheck6()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck6" duration-ms="2" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck6 -->
        <test-method status="PASS" signature="testCheck7()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck7" duration-ms="3" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck7 -->
        <test-method status="PASS" signature="testCheck8()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck8" duration-ms="2" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck8 -->
        <test-method status="FAIL" signature="testCheck9()[pri:0, instance:com.iiitb.MainClass@5d5eef3d]" name="testCheck9" duration-ms="1" started-at="2016-11-27T18:07:57Z" finished-at="2016-11-27T18:07:57Z">
          <exception class="org.junit.internal.ArrayComparisonFailure">
            <message>
              <![CDATA[arrays first differed at element [0]; expected:<10> but was:<11>]]>
            </message>
            <full-stacktrace>
              <![CDATA[arrays first differed at element [0]; expected:<10> but was:<11>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:416)
	at org.junit.Assert.assertArrayEquals(Assert.java:427)
	at com.iiitb.MainClass.testCheck9(MainClass.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.AssertionError: expected:<10> but was:<11>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.internal.ArrayComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck9 -->
      </class> <!-- com.iiitb.MainClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
